version: "3.5"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres_password
  testDB:
    image: "postgres:latest"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=postgres_password
